# Generated by Django 6.0.6 on 2026-06-19 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=60)),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='accounts.casal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=160)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantidade_parcelas', models.PositiveSmallIntegerField(default=1)),
                ('data_compra', models.DateField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('QUITADA', 'Quitada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=10)),
                ('origem', models.CharField(choices=[('AVULSA', 'Avulsa'), ('RECORRENTE', 'Recorrente')], default='AVULSA', max_length=12)),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='accounts.casal')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.categoria')),
                ('pago_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_pagas', to='accounts.membrocasal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DespesaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=160)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dia_vencimento', models.PositiveSmallIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorrentes', to='accounts.casal')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.categoria')),
                ('pago_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.membrocasal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='expenses.compra')),
            ],
            options={
                'ordering': ['data_vencimento'],
                'unique_together': {('compra', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Rateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('percentual_aplicado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_devido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status_pagamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rateios', to='accounts.membrocasal')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='expenses.parcela')),
            ],
            options={
                'unique_together': {('parcela', 'membro')},
            },
        ),
    ]
